ALTER TABLE `regions` DROP FOREIGN KEY `regions_ibfk_1`; 
ALTER TABLE `regions` ADD CONSTRAINT `regions_ibfk_1` FOREIGN KEY (`ID_ParentRegion`) REFERENCES `regions`(`ID_Region`) ON DELETE RESTRICT ON UPDATE SET NULL;
ALTER TABLE `regions` DROP FOREIGN KEY `regions_ibfk_1`; 
ALTER TABLE `regions` ADD CONSTRAINT `regions_ibfk_1` FOREIGN KEY (`ID_ParentRegion`) REFERENCES `regions`(`ID_Region`) ON DELETE SET NULL ON UPDATE SET NULL;
ALTER TABLE `categories` DROP FOREIGN KEY `categories_ibfk_1`; 
ALTER TABLE `categories` ADD CONSTRAINT `categories_ibfk_1` FOREIGN KEY (`ID_ParentCategories`) REFERENCES `categories`(`ID_Category`) ON DELETE SET NULL ON UPDATE SET NULL;
ALTER TABLE `areaplants` DROP FOREIGN KEY `areaplants_ibfk_1`; 
ALTER TABLE `areaplants` ADD CONSTRAINT `areaplants_ibfk_1` FOREIGN KEY (`ID_Region`) REFERENCES `regions`(`ID_Region`) ON DELETE CASCADE ON UPDATE CASCADE; 
ALTER TABLE `areaplants` DROP FOREIGN KEY `areaplants_ibfk_2`; 
ALTER TABLE `areaplants` ADD CONSTRAINT `areaplants_ibfk_2` FOREIGN KEY (`ID_Plant`) REFERENCES `plants`(`ID_Plant`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `changelogs` DROP FOREIGN KEY `changelogs_ibfk_1`; 
ALTER TABLE `changelogs` ADD CONSTRAINT `changelogs_ibfk_1` FOREIGN KEY (`ID_AreaPlants`) REFERENCES `areaplants`(`ID_AreaPlants`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `plants` DROP FOREIGN KEY `plants_ibfk_1`; 
ALTER TABLE `plants` ADD CONSTRAINT `plants_ibfk_1` FOREIGN KEY (`ID_Category`) REFERENCES `categories`(`ID_Category`) ON DELETE SET NULL ON UPDATE SET NULL;